import os
from conan import ConanFile
from conan.tools.cmake import CMake, CMakeToolchain, cmake_layout
from conan.tools.files import copy


class DuerwenWakeupDOAConan(ConanFile):
    name = "duerwen_wakeup_doa"
    version = "1.0.0"
    license = "Proprietary"
    description = (
        "Duerwen Wake-Word Detection and Direction-of-Arrival (DOA) library. "
        "On ARM targets the original prebuilt shared library is used; "
        "on all other architectures a no-op stub is compiled from source."
    )
    url = ""
    package_type = "shared-library"
    settings = "os", "compiler", "arch", "build_type"
    exports_sources = "CMakeLists.txt", "src/*", "include/*", "lib/*"

    @property
    def _is_arm(self):
        """True for any ARM architecture (armv7, armv7hf, armv8 / aarch64, …)."""
        return str(self.settings.arch).startswith("arm")

    def layout(self):
        cmake_layout(self)

    def generate(self):
        if not self._is_arm:
            tc = CMakeToolchain(self)
            tc.generate()

    def build(self):
        if not self._is_arm:
            cmake = CMake(self)
            cmake.configure()
            cmake.build()

    def package(self):
        # Always export public headers
        copy(self, "*.h",
             src=os.path.join(self.source_folder, "include"),
             dst=os.path.join(self.package_folder, "include"))

        if self._is_arm:
            # Use the original prebuilt binary
            copy(self, "libduerwen_wakeup_DOA.so",
                 src=os.path.join(self.source_folder, "lib"),
                 dst=os.path.join(self.package_folder, "lib"))
        else:
            # Use the stub built by CMake
            copy(self, "*.so",
                 src=self.build_folder,
                 dst=os.path.join(self.package_folder, "lib"),
                 keep_path=False)
            copy(self, "*.so.*",
                 src=self.build_folder,
                 dst=os.path.join(self.package_folder, "lib"),
                 keep_path=False)

    def package_info(self):
        if self._is_arm:
            self.cpp_info.libs = ["duerwen_wakeup_doa"]
        # CMake targets generated by CMakeDeps:  duerwen_wakeup_doa::duerwen_wakeup_doa
        self.cpp_info.set_property("cmake_file_name",   "duerwen_wakeup_doa")
        self.cpp_info.set_property("cmake_target_name", "duerwen_wakeup_doa::duerwen_wakeup_doa")
